name: CI/CD

on:
  push:
    branches:
      - '*'  # запускать на все ветки
  pull_request:
    branches:
      - '*'  # запускать при создании PR

jobs:
  lint:
    name: Проверка стилей и линтеров
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Установка зависимостей
        run: |
          pip install flake8 isort black mypy
      - name: Проверка flake8
        run: |
          flake8 .
      - name: Проверка isort
        run: |
          isort --check-only --diff .
      - name: Проверка black
        run: |
          black --check .
      - name: Проверка mypy
        run: |
          mypy .
